#!/usr/bin/env python3

import json
import sys

from simple_blog_generator import simple_blog_generator


if __name__ == "__main__":

    if len(sys.argv) != 2:
        print("Error: No config file supplied")
        print("Usage: simple_blog_generator.py <path_to_config_file>")
        exit(1)

    with open(sys.argv[1], "r") as config_file:
        settings = json.load(config_file)

    blog = simple_blog_generator.SimpleBlogGenerator(**settings)
    blog.generate()
